##################################################
# This is auto generated by code.
##################################################

import base64
import inspect
import math
import os
import typing
import cv2
import numpy as np
import robot
import selenium
import lxml.html as html
import selenium.webdriver as webdriver
import RobotFrameworkBasic
import robot.libraries.BuiltIn
import typing as typing.Dict[str, selenium.webdriver.chrome.webdriver
import selenium.webdriver.remote.webelement
import lxml.html
import numpy
from SeleniumLibrary import SeleniumLibrary

RUN: str
class BasicCommon(RobotFrameworkBasic.RobotBasic):
	driver: property
	action_chains: property
	_driver_dict_value: property
	def __init__(self):
		super().__init__()
		self.built: robot.libraries.BuiltIn.BuiltIn =  getattr(self, 'built', None)
		self.selenium_lib: SeleniumLibrary =  getattr(self, 'selenium_lib', None)
		self._driver_dict: typing.Dict[str, selenium.webdriver.chrome.webdriver.WebDriver] =  getattr(self, '_driver_dict', {})
		self._driver_key: typing.Optional[str] =  getattr(self, '_driver_key', None)
		self.screenshot_root: str =  getattr(self, 'screenshot_root', None)
		self.outer_coordinate: typing.Tuple[float] =  getattr(self, 'outer_coordinate', None)
		self.inner_coordinate: typing.Tuple[float] =  getattr(self, 'inner_coordinate', None)
		self.window_x: float =  getattr(self, 'window_x', None)
		self.window_y: float =  getattr(self, 'window_y', None)
	def selenium_init(self, screenshot_dir: str = '.', _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param screenshot_dir: screenshot存储路径
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def _create_driver_alias(self, alias = None, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.Tuple[bool, str]:
		"""
		根据alias确实是否已经生成，如果不输入，那么将会自动生成一个没有过的值
		:param alias:
		:return: bool,str 是否已经生成了，目标alias名。
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_create_webdriver(self, driver_name: str = 'Chrome', alias = None, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None, **kwargs):
		"""
		:param driver_name: Chrome,Ie,Edge,Firefox,Safari,WebKitGTK,WPEWebKit
		:param alias: 标记名称，如果不填写的话，会默认按照_0、_1的逻辑无限循环增加下去
		:param kwargs: 其他driver参数
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def _close_webdriver_by_key(self, key, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		把目标driver整个quit掉
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def _close_window_by_key(self, key, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_switch_to_driver_by_alias(self, alias: str, error_when_not_find: bool = True, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		将当前的driver切换到alias对应的driver
		:param alias:
		:param error_when_not_find:
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_close_webdriver(self, alias = None, close_all_windows: bool = True, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		删除
		:param alias:
		:param close_all_windows:会尝试关闭所有的窗口
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_check_window_handles(self, alias = None, quit_driver: bool = True, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		检查当前的windows handle是不是匹配。如果不匹配那么进行增删。仅处理当前的webdriver
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_set_current_window_by_alias(self, window_alias, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		给当前的window设置别名
		:param window_alias:
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_set_index_window_by_alias(self, window_alias, window_index = -1, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		给目标index的window设置别名，一般是设置最后一个
		:param window_alias:
		:param window_index:
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_switch_to_window_by_index(self, window_index: int, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_switch_to_window_by_alias(self, window_alias: str, error_when_not_find: bool = True, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		按照别名将window切换过去
		:param window_alias:
		:param error_when_not_find: 如果没有找到，那么是否报错
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_switch_to_window_by_handle(self, window_handle: str, error_when_not_find: bool = True, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		根据handle来切换
		:param window_handle:
		:param error_when_not_find: 如果没有找到，那么是否报错
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_get_window_handle_by_alias(self, window_alias: str, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_get_window_handle_by_index(self, index: int, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_get_target_window_title_by_handle(self, window_handle: str, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> str:
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_get_all_window_title(self, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.Dict[str, str]:
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_close_window(self, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		把current window关了
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_analyse_locator(self, locator: typing.Union[str, list, set, tuple], _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.Tuple[str, str]:
		"""
		将locator文本解析为by,path，方便find element
		:param locator: 合并的locator
		:return:
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_find_elements_by_locator(self, locator, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.List[selenium.webdriver.remote.webelement.WebElement]:
		"""
		:param locator: by=path
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_find_element_by_locator(self, locator, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> selenium.webdriver.remote.webelement.WebElement:
		"""
		:param locator: by=path
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_html_find_element_by_locator(self, locator, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> lxml.html.HtmlElement:
		"""
		:param locator: by=path
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_html_find_elements_by_locator(self, locator, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.List[lxml.html.HtmlElement]:
		"""
		使用html的方法检查页面内是否存在某个元素
		:param locator: 目标元素或locator
		:return: 搜素结果
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_execute_js_script(self, js_code: str, *args, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.Any:
		"""
		:param js_code: javascript脚本文本
		:param args: 其他相应的参数
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def analyse_color_function(self, color_function, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.Callable[[int, int, int], bool]:
		"""
		:param color_function: 输入的符号+数值，例如 >60,>60,>60
		:return: 相应的判定函数
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def exchange_list3_to_color_function(self, formula_list, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.Callable[[int, int, int], bool]:
		"""
		:param formula_list: 已经解析清晰的列表
		:return: 相应的判定函数
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_get_full_screenshot_path(self, screenshot_name, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> str:
		"""
		:param screenshot_name: 截图存储文件夹名
		:return: 截屏文件夹全路径
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_cut_screenshot(self, screenshot_locator = None, image_name = 'element-cut-image.png', _show_return_info = False, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param screenshot_locator: 截图目标，不输入则全浏览器截屏
		:param image_name: 存储的文件名称
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def test123(self, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_take_screenshot(self, screenshot_locator = None, image_name = 'python-screenshot.png', rename = True, _show_return_info = False, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param screenshot_locator: 截图目标，不输入则全浏览器截屏
		:param image_name: 存储的文件名称
		:param rename: 如果重名了，是否通过增加序号的方式重命名
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_log_screenshot(self, screenshot_locator = None, _show_return_info = False, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> numpy.ndarray:
		"""
		:param screenshot_locator: 截图目标，不输入则全浏览器截屏
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_log_screenshot_path(self, screenshot_name, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> None:
		"""
		:param screenshot_name: 截图存储文件夹名称
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_analyse_image(self, image, _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None):
		"""
		:param image: 目标图片的路径
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_analyse_element(self, locator: typing.Union[selenium.webdriver.remote.webelement.WebElement, str], _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> selenium.webdriver.remote.webelement.WebElement:
		"""
		:param locator: locator或者element
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_analyse_elements(self, locator: typing.Union[typing.List[selenium.webdriver.remote.webelement.WebElement], str], _return_when_error = None, _log_keyword_structure = True, _return_name = None, _show_return_info = None, _simple_doc = False, _debug_default = None, _debug_debug = None, _force_raise = None) -> typing.List[selenium.webdriver.remote.webelement.WebElement]:
		"""
		:param locator: locator或者elements
		:param _return_when_error: 输入任意非None值后，当error发生时，不再raise error，而是返回这个值
		:param _log_keyword_structure: bool : 默认True，生成一组robotframework格式的可展开的日志。如果False时，就不会把这个函数做成折叠状，而是只打印一些内容
		:param _return_name: str : 你可以把代码中这个函数赋值的变量str写在这儿，来让日志更加贴近python代码内容
		:param _show_return_info: bool :默认True，是否把return的信息打印出来。
		:param _simple_doc: bool :默认False，是否仅打印第一行doc信息
		:param _debug_default:在不唤醒UI时，遇上error的处理逻辑，0/1为上报错误；2为跳过错误；默认1,
		:param _debug_debug：在会唤醒UI时，遇上error的处理逻辑，0为弹出UI进行处理；1为不弹出UI并向上报错；2为不弹出UI，也不向上报错；默认为0
		:param _force_raise：设置为True后，可以让它的所有的子函数全部都主动raise error，而不是弹出窗口或跳过错误；默认为False
		"""
		...
	def selenium_debug_teardown(self, function, args, kwargs, re_value, error, trace_back, has_return):
		"""
		通用的debug teardown函数
		:param function: 函数
		:param args: args参数
		:param kwargs: kwargs参数
		:param re_value: 对应的返回值
		:param error: 弹出的报错，没报错就None
		:param trace_back: 弹出的报错的traceback，没报错就None
		:param has_return: 是否有返回值
		:return:
		"""
		...
	...

